config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :hostels, only: [:new, :create, :edit, :update, :destroy]
    resources :cities, only: [:new, :create, :edit, :update, :destroy]
    resources :regions, only: [:new, :create, :edit, :update, :destroy]
    resources :countries, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :hostels, only: [:index, :show]
  resources :cities, only: [:index, :show]
  resources :regions, only: [:index, :show]
  resources :countries, only: [:index, :show]

  root 'index#index'
  get 'index/about' => 'index#about', :as => :index_about
  get 'index/generate' => 'index#generate', :as => :index_generate

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= nav_bar brand: t(:title), brand_link: root_path, responsive: true do %>
    <%= menu_group pull: :right do %>
      <%= menu_item t(:home), root_path %>
      <%= menu_item t(:about), index_about_path %>
      <% if user_signed_in? %>
        <%= menu_item t(:log_out) + ' ' + current_user.email + ')', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= menu_item t(:log_in), new_user_session_path %>
      <% end %>
    <% end %>
  <% end %>
  <div class="container border-container">
    <div class="row">
      <div class="col-md-4">
        <div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title"><%= t 'Menu' %></h3></div>
          <div class="table">
            <ul class="nav nav-pills nav-stacked kv-sidenav">
              <%= menu_item content_tag(:i, '', :class => 'fa fa-home') + ' ' + t(:home), root_path %>
              <%= menu_item content_tag(:i, '', :class => 'fa fa-pencil-square-o') + ' ' + t(:countries), countries_path %>
              <%= menu_item content_tag(:i, '', :class => 'fa fa-pencil-square-o') + ' ' + t(:regions), regions_path %>
              <%= menu_item content_tag(:i, '', :class => 'fa fa-pencil-square-o') + ' ' + t(:cities), cities_path %>
              <%= menu_item content_tag(:i, '', :class => 'fa fa-pencil-square-o') + ' ' + t(:hostels), hostels_path %>
            </ul>
          </div>
        </div>
    </div>
    <div class="col-md-8">
      <%= render_breadcrumbs nil%>
      <%= yield %>
    </div>
  </div>
  </div>
</body>
</html>